const package = require('./package.json')
console.log('name', package.name)
console.log('version', package.version)
console.log('language version', process.version)
console.log('PLATFORM', process.platform)
const os = require('os')
console.log(os.type())
console.log(os.release())
console.log(os.platform())
console.log(os.hostname())